version: '3'

services:
    hw_server_1:
        image: hw_server:1        
    proxy_server:
        image: nginx:latest
        volumes:
            - ./proxy_nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - 80:8080
